### ISSUE TITLE
[Optional] Add function to download policy templates

### ISSUE THREAD

**Issue by kowith337** [UndertakerBen/PorEdgeUpd#11]
Even I'm just a single home user, but I want to config browser more than limitations of config in the browser through Group policy templates.

Unfortunately, downloading policy templates for edge is not easy as Chrome that already have a static [page](https://www.chromium.org/administrators/policy-templates) and URL path to download and then extract for update templates if needed, while in edge is need to go to [business download](https://www.microsoft.com/en-us/edge/business/download) page and take more clicks, start from select builds, architecture, versions, etc. even you can click "Get policy files", it's also require to read their terms, too.
After that, if the browser get update and need to update policy templates too, you need to redo that step start from go to edge business download page onward again and again...

Note that configure edge with policy level require non-home edition of Windows.

**Comment by UndertakerBen** [comment]
I created a version of the Portable Updater with optional download for the group policy templates and published it as a prerelease.
It only downloads the zip file to a folder and does not extract or install it.

https://github.com/UndertakerBen/PorEdgeUpd/releases/tag/v1.4.0.0

**Comment by kowith337** [comment]
Thanks for test build, even though the test client won't extract template, but for now I can combo with batch file to copy policy definitions manually and it seems enough for me.
