### ISSUE TITLE
404 Not Found on startup

### ISSUE THREAD

**Issue by thatsprettygood** [UndertakerBen/PorEdgeUpd#16]
From the past few days ago, two 404 errors appear at startup when I launch the updater.
I use Canary, so it doesn't effect me. (as far a I know) But I suspect they changed their downloads links.

**Comment by Scoty43** [comment]
Get the same. Remoteserver not aviable.

**Comment by mainufer** [comment]
I get the same issues since 1 or two weeks. I was wondering how to extract the download links, so I can download the extraction files for myself.

**Comment by thatsprettygood** [comment]
He just released a new update, but all it is that it suppresses the errors now..
I don't know if this fixed the problem.

**Comment by mainufer** [comment]
Hi there, just tested the new version and the error message is not showing up again. Not sure, if updates are still working. Will keep testing and see if there is a new Canary version available. Thx for the update !

**Comment by thatsprettygood** [comment]
I went into the code and found the API that checks for the latest version.
https://www.microsoftedgeinsider.com/api/versions
![image](https://user-images.githubusercontent.com/36249601/155455398-a37e0a08-c7f6-41d3-8906-d366d8cfdbe2.png)
It says here that the Canary branch is on 100.0.1174.0, but in the launcher, it only shows 100.0.1169.0.
![image](https://user-images.githubusercontent.com/36249601/155455459-5b69d712-f05a-4e85-8796-7b0705993aed.png)
Is this true for you, @mainufer?

**Comment by mainufer** [comment]
@thatsprettygood That's what I was afraid of: The canary branch isn't updating. That's what I see: 
![image](https://user-images.githubusercontent.com/45529131/155467805-cc5fc535-d67b-4078-9460-26e13a8b8c36.png)

**Comment by mainufer** [comment]
Good morning. Just a quick info: The new edge versions are showing up the updater. Seems, everything is OK now ! 
![image](https://user-images.githubusercontent.com/45529131/155658504-1c9e0e93-9f0c-48e3-8a61-fd62ba1b8dfe.png)

**Comment by thatsprettygood** [comment]
@mainufer That is also true for me, thanks!
