### ISSUE TITLE
Register Edge Portable with Default Programs or Default Apps in Windows

### ISSUE THREAD

**Issue by sun1ight** [UndertakerBen/PorEdgeUpd#2]
Please make it possible to register Edge Portable launcher using default programs or default applications, to open external links and files on same profile, like this https://www.winhelponline.com/blog/register-firefox-portable-with-default-programs-in-vista/

**Comment by UndertakerBen** [comment]
I already have it in planning, but it will take some more time until I can publish it.

**Comment by TheBestPessimist** [comment]
I believe this is done and can be closed.
