### ISSUE TITLE
”PlayReady Hardware DRM support“ does not work in the portable version

### ISSUE THREAD

**Issue by lkmvip** [UndertakerBen/PorEdgeUpd#4]
can fix it？
![123](https://user-images.githubusercontent.com/12974141/83989761-0a2c4880-a97a-11ea-8aac-456a751e8a06.png)

**Comment by UndertakerBen** [comment]
Sorry! I can't fix this on my end. Your graphics card or the card driver does not support this function. Because on my PC this is set to "true".
![GameReady DRM](https://user-images.githubusercontent.com/60009857/84012163-6f326f00-a977-11ea-9be1-3ccb30541606.JPG)

**Comment by lkmvip** [comment]
thank you , 
It should be my system problem, V79 can display true
