### ISSUE TITLE
Unhandled exception 404 Not found error running updater

### ISSUE THREAD

**Issue by juanmbt** [UndertakerBen/PorEdgeUpd#5]
When launching the updated I got a pop-up window with error message. aprox translation as my system is in Spanish:

Connection terminated: Unexpected error sent.
![image](https://user-images.githubusercontent.com/21691159/85148436-c2c57800-b215-11ea-98b6-beb2c272af68.png)

After clicking on the (Accept button), the updater opens without showing the current version:
![image](https://user-images.githubusercontent.com/21691159/85148592-f0122600-b215-11ea-9373-80a5ca3c1893.png)

And clicking on the button to download the new version throws an exception. With error message:
Remote server error: (404) Not found.

My system is configured in Spanish, so some of the error messages are translated.
```
System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.HttpWebRequest.GetResponse()
   en Edge_Updater.Form1.<DownloadFile>d__23.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Edge_Updater.Form1.<NewMethod1>d__42.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Edge_Updater.Form1.<Button8_Click>d__20.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

This started happening Today.

**Comment by juanmbt** [comment]
Updater was updated today to version 1.3.5.5

Now I'm getting this popup when running it:
![image](https://user-images.githubusercontent.com/21691159/85217131-0245ae80-b353-11ea-9412-7b8dd64c9b56.png)

Looks like something is blocking my connection to the server to perform a version check.

**Comment by UndertakerBen** [comment]
Yes, I think something is blocking your connection to "msedge.api.cdp.microsoft.com". But I don't know what's blocking it. Maybe a firewall, an anti-virus or a proxy server.
I can't reproduce that on my computer.

**Comment by juanmbt** [comment]
Looks like the server is down or inestable:
![image](https://user-images.githubusercontent.com/21691159/85304633-96a63300-b471-11ea-9bae-a4df440252c5.png)

I was able to update without issues a couple of weeks ago. It doesn't look like a DNS issue as it resolves correctly.

**Comment by UndertakerBen** [comment]
Now i had the same problem as you. I hopefully fixed the updater by adding the security protocol type Tls12 to retrieve the current version numbers.

**Comment by juanmbt** [comment]
I just tested the most recent version of the updater. It is working fine now without errors.

Thanks for the support.
