### ISSUE TITLE
Remote Server are offline

### ISSUE THREAD

**Issue by Scoty43** [UndertakerBen/PorEdgeUpd#8]
Whene i open the portable update i get the message the remote server is offline.

**Comment by UndertakerBen** [comment]
I just updated the updater to version 1.3.7.0. I hope it works again.
I have changed the version query.

**Comment by Scoty43** [comment]
Now i get error whene i make a update.

![{8AB81240-28E9-4BDD-AC10-104034595F06}](https://user-images.githubusercontent.com/25227541/104001594-2c03dd00-51a0-11eb-834a-86f8725da0d0.png)

**Comment by UndertakerBen** [comment]
Can you please test this version.
[Portable Edge (Chromium) Updater v1.3.7.1.zip](https://github.com/UndertakerBen/PorEdgeUpd/files/5786674/Portable.Edge.Chromium.Updater.v1.3.7.1.zip)

In this version i have added a User-Agent for getting the download link.
Or is a tool blocking the gateway to "msedge.api.cdp.microsoft.com".

**Comment by Scoty43** [comment]
> Can you please test this version.
> [Portable Edge (Chromium) Updater v1.3.7.1.zip](https://github.com/UndertakerBen/PorEdgeUpd/files/5786674/Portable.Edge.Chromium.Updater.v1.3.7.1.zip)
> 
> In this version i have added a User-Agent for getting the download link.
> Or is a tool blocking the gateway to "msedge.api.cdp.microsoft.com".

This working now.

**Comment by UndertakerBen** [comment]
Thanks for testing this version. I have now released this version.

**Comment by Scoty43** [comment]
Die Meldung mit dem Remote Server ist wieder da. 

![image](https://user-images.githubusercontent.com/25227541/104085395-61b3cf00-524f-11eb-8438-35430a34ed96.png)

**Comment by UndertakerBen** [comment]
Irgendwie bin ich jetzt Ratlos und mir fällt nichts mehr dazu ein.
Irgendetwas muss da Lokal die Verbindung zu dem Server verhindern. Da ich es hier wirklich nicht reproduziert bekomme, oder läuft die Verbindung über einen Proxy-Server. Von Proxy-Servern und seiner Arbeitsweise habe ich absolut keine Ahnung.

**Comment by Scoty43** [comment]
Nein verwendet keinen Proxy. Hab eine ganz normale Kabel Verbindung. Gestern konnte ich noch Updates machen und heute nicht mehr.

**Comment by Scoty43** [comment]
Ok i have solved the problem. The problem was on my site sorry. I have reset my firewall rules and now all woking normal. I dont know why have block the firewall all MS content.
